=== DSpace/DSpace/dspace/config/input-forms.dtd
<!-- DSpace Custom Submit input form definition language -->


 <!ELEMENT input-forms (form-map, form-definitions, form-value-pairs) >

 <!ELEMENT form-map (name-map)* >
 <!ELEMENT name-map EMPTY >
 <!ATTLIST name-map 
           collection-handle CDATA #REQUIRED
           form-name NMTOKEN #REQUIRED>

 <!ELEMENT form-definitions (form)+ >
 <!ELEMENT form (page)+ >
 <!ATTLIST form name NMTOKEN #REQUIRED>
 <!ELEMENT page (field)+ >
 <!ATTLIST page number NMTOKEN #REQUIRED>
 <!ELEMENT field (dc-schema, dc-element, dc-qualifier?, repeatable?, label, input-type, hint, required?, vocabulary?) >
 <!ELEMENT dc-schema (#PCDATA) >
 <!ELEMENT dc-element (#PCDATA) >
 <!ELEMENT dc-qualifier (#PCDATA) >
 
 <!ELEMENT repeatable (#PCDATA) >
 <!ELEMENT label (#PCDATA) >
 <!ELEMENT input-type (#PCDATA)>
  
 <!ELEMENT hint (#PCDATA) >
 <!ELEMENT required (#PCDATA)>

 <!ELEMENT form-value-pairs (value-pairs)* >
 <!ELEMENT value-pairs (pair)+ >

 <!-- ***
        To assign a particular 'value-pairs' list to a particular dropdown 'input-type'
        field, as found on a particular form, put:
        - value-pairs/@value-pairs-name string into
           form/page/field/input-type/@value-pairs-name
        - form/page/field/@DCelement + '_' + form/field/DCqualifier into
           value-pairs/@dc-term
             (e.g. 'language_iso')
  -->
 <!ATTLIST value-pairs value-pairs-name CDATA #REQUIRED
                            dc-term   CDATA #REQUIRED
 >
  
 <!ELEMENT pair (displayed-value,stored-value) >
 <!ELEMENT displayed-value (#PCDATA)>
 <!ELEMENT stored-value (#PCDATA)>

 <!ATTLIST input-type value-pairs-name CDATA  #IMPLIED>

 <!ELEMENT vocabulary (#PCDATA) >

=== DSpace/DSpace/dspace/config/input-forms_uk.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE input-forms SYSTEM "input-forms.dtd">


<input-forms>

    <!-- The form-map maps collection handles to forms. DSpace does not       -->
    <!-- require that a collection's name be unique, even within a community .-->
    <!-- DSpace does however insure that each collection's handle is unique.  -->
    <!-- Form-map provides the means to associate a unique collection name    -->
    <!-- with a form. The form-map also provides the special handle "default" -->
    <!-- (which is never a collection), here mapped to "traditional". Any     -->
    <!-- collection which does not appear in this map will be associated with -->
    <!-- the mapping for handle "default".                                    -->

    <form-map>
        <name-map collection-handle="default" form-name="traditional" />
    </form-map>


    <!-- The form-definitions map lays out the detailed definition of all the -->
    <!-- submission forms.Each separate form set has a unique name as an      -->
    <!-- attribute. This name matches one of the names in the form-map. One   -->
    <!-- named form set has the name "traditional"; as this name suggests,    -->
    <!-- it is the old style and is also the default, which gets used when    -->
    <!-- the specified collection has no correspondingly named form set.      -->
    <!--                                                                      -->
    <!-- Each form set contains an ordered set of pages; each page defines    -->
    <!-- one submission metadata entry screen. Each page has an ordered list  -->
    <!-- of field definitions, Each field definition corresponds to one       -->
    <!-- metatdata entry (a so-called row), which has a DC element name, a    -->
    <!-- displayed label, a text string prompt which is called a hint , and   -->
    <!-- an input-type. Each field also may hold optional elements: DC        -->
    <!-- qualifier name, a repeatable flag, and a text string whose presence  -->
    <!-- serves as a 'this field is required' flag.                           -->

    <form-definitions>

        <form name="traditional">
            <page number="1">
                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>contributor</dc-element>
                    <dc-qualifier>author</dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Автори</label>
                    <input-type>name</input-type>
                    <hint>Введіть авторів цього матеріалу.</hint>
                    <required></required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>title</dc-element>
                    <dc-qualifier></dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>Назва</label>
                    <input-type>onebox</input-type>
                    <hint>Введіть основну назву.</hint>
                    <required>Ви повинні ввести основну назву для цього матеріалу.</required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>title</dc-element>
                    <dc-qualifier>alternative</dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Інші назви</label>
                    <input-type>onebox</input-type>
                    <hint>Введіть іншу назву (якщо є).</hint>
                    <required></required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>date</dc-element>
                    <dc-qualifier>issued</dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>Дата публікації</label>
                    <input-type>date</input-type>
                    <hint>Введіть дату публікації.</hint>
                    <required>Вам необхідно ввести хоча б рік.</required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>publisher</dc-element>
                    <dc-qualifier></dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>Видавець</label>
                    <input-type>onebox</input-type>
                    <hint>Вкажіть, де раніше видавався документ</hint>
                    <required></required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>identifier</dc-element>
                    <dc-qualifier>citation</dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>Бібліографічний опис</label>
                    <input-type>textarea</input-type>
                    <hint>Введіть стандартний бібліографічний опис для попередьо випущеного примірника цього матеріалу.</hint>
                    <required></required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>speciality</dc-element>
                    <dc-qualifier>id</dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>Спеціальність</label>
                    <input-type>onebox</input-type>
                    <hint></hint>
                    <required></required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>type</dc-element>
                    <dc-qualifier></dc-qualifier>
                    <repeatable>true</repeatable>
                    <label>Вид документа</label>
                    <input-type value-pairs-name="common_types">dropdown</input-type>
                    <hint>Виберіть тип(и) змісту матеріалу. Щоб вибрати більш ніж одне значення у списку, Вам необхідно тримати натиснутою клавішу [CTRL] або ж [Shift].</hint>
                    <required>Виберіть тип(и) змісту матеріалу</required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>date</dc-element>
                    <dc-qualifier>presentation</dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>Дата захисту</label>
                    <input-type>onebox</input-type>
                    <hint></hint>
                    <required></required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>language</dc-element>
                    <dc-qualifier>iso</dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>Мова</label>
                    <input-type value-pairs-name="common_iso_languages">dropdown</input-type>
                    <hint>Виберіть мову основного змісту матеріалу. Якщо у списку нижче немає відповідної мови, будь ласка, вибирайте 'Інша мова'.
                        Якщо зміст матеріалу насправді не містить мову (наприклад, якщо це набір даних чи зображення), будь ласка, вибирайте 'Невизначено'.</hint>
                    <required></required>
                </field>
                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>rights</dc-element>
                    <dc-qualifier>uri</dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>Ліцензія</label>
                    <input-type value-pairs-name="license">dropdown</input-type>
                    <hint></hint>
                    <required></required>
                </field>
            </page>

            <page number="2">
                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>subject</dc-element>
                    <dc-qualifier></dc-qualifier>
                    <!-- An input-type of twobox MUST be marked as repeatable -->
                    <repeatable>true</repeatable>
                    <label>Ключові слова</label>
                    <input-type>threelocbox</input-type>
                    <hint>Введіть нижче відповідні матеріалу ключові слова. Кожне ключове слово або фраза заносяться в окремий рядок з маленької літери. </hint>
                    <required></required>
                    <vocabulary>srsc</vocabulary>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>description</dc-element>
                    <dc-qualifier>abstract</dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>Анотація</label>
                    <input-type>textarea</input-type>
                    <hint>Введіть нижче короткий зміст (резюме) для матеріалу. </hint>
                    <required></required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>description</dc-element>
                    <dc-qualifier>sponsorship</dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>Спонсорська підтримка</label>
                    <input-type>textarea</input-type>
                    <hint>Введіть нижче у текстове поле імена/найменування будь-яких спосорів та/чи коди фондів. </hint>
                    <required></required>
                </field>

                <field>
                    <dc-schema>dc</dc-schema>
                    <dc-element>description</dc-element>
                    <dc-qualifier></dc-qualifier>
                    <repeatable>false</repeatable>
                    <label>Опис</label>
                    <input-type>textarea</input-type>
                    <hint>Введіть нижче будь-який інший опис чи зміст, посилання, коментарі тощо. </hint>
