=== DSpace/DSpace/dspace/config/item-submission.dtd
<!-- DSpace Custom Item Submission Process definition language -->
<!--                                                           -->
<!-- This DTD defines the format for the DSpace                -->
<!-- 'config/item-submission.xml' configuration file           -->

 <!-- Root element is 'item-submission' -->
 <!ELEMENT item-submission (submission-map, step-definitions, submission-definitions) >

 <!-- 'submission-map' must contain one or more 'name-map' nodes -->
 <!ELEMENT submission-map (name-map+) >
 
 <!ELEMENT name-map EMPTY >
 <!ATTLIST name-map 
           collection-handle CDATA #REQUIRED
           submission-name NMTOKEN #REQUIRED>

 <!-- 'step-definitions' must contain at least one 'step' node -->
 <!-- (The "select collection" step *must* be here)            -->
 <!ELEMENT step-definitions (step+) >
 
 <!ELEMENT step (heading?, processing-class, type, scope?) >
 <!ATTLIST step 
 		   id NMTOKEN #REQUIRED
 		   mandatory NMTOKEN #IMPLIED>
 
 <!ELEMENT heading (#PCDATA) >
 <!ELEMENT processing-class (#PCDATA)>
 <!ELEMENT type (#PCDATA)>
 <!ELEMENT scope (#PCDATA)>
 <!ATTLIST scope 
 		   visibility NMTOKEN #IMPLIED 
 		   visibilityOutside NMTOKEN #IMPLIED>
 
 <!-- 'submission-definitions' must contain at least one       -->
 <!-- 'submission-process' node                                -->
 <!ELEMENT submission-definitions (submission-process+)>
 
 <!ELEMENT submission-process (step+)>
 <!ATTLIST submission-process name NMTOKEN #REQUIRED>

=== DSpace/DSpace/dspace/config/item-submission.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE item-submission SYSTEM "item-submission.dtd">

<!-- Configurable Submission configuration file -->

<!-- This XML configuration file allows you to configure the ordering -->
<!-- and number of the steps that occur in the Item Submission Process. -->
<item-submission>

    <!-- The process-map maps collection handles to a particular Item -->
    <!-- Submission Process. This requires that a collection's name be -->
    <!-- unique, even within a community. DSpace does however ensure that each -->
    <!-- collection's handle is unique. Process-map provides the means to -->
    <!-- associate a unique collection name with an Item Submission process. -->
    <!-- The process-map also provides the special handle "default" (which is -->
    <!-- never a collection), here mapped to "traditional". Any collection -->
    <!-- which does not appear in this map will be associated with the mapping -->
    <!-- for handle "default". -->
    <submission-map>
        <!-- Default submission process -->
        <name-map collection-handle="default" submission-name="traditional"/>

        <!-- Sample Entities Collection configuration based on the demo Entities dataset available at:
             https://github.com/DSpace-Labs/AIP-Files/releases/tag/demo-entities-data
             This sets up the following Entity-based Collections in that dataset:
                "Publication" Collections = "Publications" -> "Articles", "Books", "Publications 2", & "Theses"
                "OrgUnit" Collection = "Related Objects" -> "OrgUnits"
                "Person" Collections = "Related Objects" -> "People" & "People 2"
                "Project" Collections = "Related Objects" -> "Projects" & "Projects 2"
                "Journal" Collection = "Compound Journals" -> "Journals"
                "Journal Volume" Collection = "Compound Journals" -> "Journal Volumes"
                "Journal Issue" Collection = "Compound Journals" ->  "Journal Issues"
             If you are using that demo dataset, you can simply uncomment the below configuration to enable Entity
             submission into all of the above Collections.
        -->
        <!--
        <name-map collection-handle="123456789/3" submission-name="Publication"/>
        <name-map collection-handle="123456789/4" submission-name="Publication"/>
        <name-map collection-handle="123456789/281" submission-name="Publication"/>
        <name-map collection-handle="123456789/5" submission-name="Publication"/>
        <name-map collection-handle="123456789/8" submission-name="OrgUnit"/>
        <name-map collection-handle="123456789/6" submission-name="Person"/>
        <name-map collection-handle="123456789/279" submission-name="Person"/>
        <name-map collection-handle="123456789/7" submission-name="Project"/>
        <name-map collection-handle="123456789/280" submission-name="Project"/>
        <name-map collection-handle="123456789/28" submission-name="Journal"/>
        <name-map collection-handle="123456789/29" submission-name="JournalVolume"/>
        <name-map collection-handle="123456789/30" submission-name="JournalIssue"/>
        -->
        <!-- These configurations enable default submission forms per Entity type

            The  collection-entity-type will be the entity-type attribute associated with a collection,
            typically the entity name that is associated with a collection if any created or loaded
            (that is usually specified in relationship-types.xml).
            - - - - - -
            PLEASE NOTICE THAT YOU WILL HAVE TO RESTART DSPACE
            - - - - - -
        -->
        <name-map collection-entity-type="Publication" submission-name="Publication"/>
        <name-map collection-entity-type="Person" submission-name="Person"/>
        <name-map collection-entity-type="Project" submission-name="Project"/>
        <name-map collection-entity-type="OrgUnit" submission-name="OrgUnit"/>
        <name-map collection-entity-type="Journal" submission-name="Journal"/>
        <name-map collection-entity-type="JournalVolume" submission-name="JournalVolume"/>
        <name-map collection-entity-type="JournalIssue" submission-name="JournalIssue"/>
        <name-map collection-entity-type="Dataset" submission-name="Dataset"/>
            <name-map collection-entity-type="Funding" submission-name="Funding"/>

        <!-- Example of configuration using a community handle to map an Item Submission Process.

            This configuration maps the submission process to the community's descendant
            collections that do not have a mapping defined by collection-handle or entity-type

        <name-map community-handle="123456789/1234" submission-name="xxxx"/>
        -->

    </submission-map>



    <!-- The 'step-definitions' allows you to define steps which you may wish -->
    <!-- to "share" amongst multiple submission-item definitions. In order to -->
    <!-- share the same step definition, you can refer to it by its unique id -->
    <!-- defined in this section. EVERY 'step' in this section MUST have a -->
    <!-- unique identifier in the 'id' attribute! -->
    <!-- -->
    <!-- Each <step-definition> REQUIRES the following attributes (@) and properties: -->
    <!-- @id - The unique identifier for this step -->
    <!-- -->
    <!-- <processing-class> - The class which will process all information for -->
    <!-- this step. The class must implement -->
    <!-- 'org.dspace.app.rest.submit.RestProcessingStep' -->
    <!-- (or one of the org.dspace.rest.submit.step.* classes) -->
    <!-- This property should reference the full path of the class -->
    <!-- (e.g. org.dspace.app.rest.submit.step.MyCustomStep) -->
    <!-- -->
    <!-- The following properties are OPTIONAL for each <step-definition>: -->
    <!-- <heading> - References the message key, from the -->
    <!-- Messages.properties -->
    <!-- -->
    <step-definitions>
        <!-- The "collection" step is a "special step" which is *REQUIRED* -->
        <!-- In DSpace, all submitted items must be immediately assigned -->
        <!-- to a collection. This step ensures that a collection is always selected. -->
        <step-definition id="collection">
            <heading></heading>
            <processing-class>org.dspace.app.rest.submit.step.CollectionStep</processing-class>
            <type>collection</type>
        </step-definition>

        <!-- The following set of DescribeStep <step-definition>s all point to forms (of the same name) which are
             defined in submission-forms.xml -->
        <step-definition id="traditionalpageone" mandatory="true">
            <heading>submit.progressbar.describe.stepone</heading>
            <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
            <type>submission-form</type>
        </step-definition>
        <step-definition id="traditionalpagetwo" mandatory="true">
            <heading>submit.progressbar.describe.steptwo</heading>
            <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
            <type>submission-form</type>
        </step-definition>
        <step-definition id="publicationStep" mandatory="true">
            <heading>submit.progressbar.describe.stepone</heading>
            <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
            <type>submission-form</type>
        </step-definition>
        <step-definition id="personStep" mandatory="true">
            <heading>submit.progressbar.describe.stepone</heading>
            <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
            <type>submission-form</type>
        </step-definition>
        <step-definition id="projectStep" mandatory="true">
            <heading>submit.progressbar.describe.stepone</heading>
            <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
            <type>submission-form</type>
        </step-definition>
        <step-definition id="orgUnitStep" mandatory="true">
            <heading>submit.progressbar.describe.stepone</heading>
            <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
            <type>submission-form</type>
        </step-definition>
        <step-definition id="journalStep" mandatory="true">
            <heading>submit.progressbar.describe.stepone</heading>
            <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
            <type>submission-form</type>
        </step-definition>
        <step-definition id="journalVolumeStep" mandatory="true">
            <heading>submit.progressbar.describe.stepone</heading>
            <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
            <type>submission-form</type>
        </step-definition>
        <step-definition id="journalIssueStep" mandatory="true">
            <heading>submit.progressbar.describe.stepone</heading>
            <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
            <type>submission-form</type>
        </step-definition>
        <step-definition id="datasetStep" mandatory="true">
            <heading>submit.progressbar.describe.stepone</heading>
            <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
            <type>submission-form</type>
        </step-definition>
        <step-definition id="fundingStep" mandatory="true">
            <heading>submit.progressbar.describe.stepone</heading>
            <processing-class>org.dspace.app.rest.submit.step.DescribeStep</processing-class>
            <type>submission-form</type>
        </step-definition>

        <step-definition id="upload">
            <heading>submit.progressbar.upload</heading>
