=== DSpace/DSpace/dspace-api/src/test/data/dspaceFolder/config/entities/relationship-types.dtd
<!-- Build relationships from XML -->


<!ELEMENT relationships (type)*>
<!ELEMENT type (leftType|rightType|leftwardType|rightwardType|leftCardinality|rightCardinality)*>
<!ELEMENT leftType (#PCDATA)>
<!ELEMENT rightType (#PCDATA)>
<!ELEMENT leftwardType (#PCDATA)>
<!ELEMENT rightwardType (#PCDATA)>
<!ELEMENT leftCardinality (min|max)*>
<!ELEMENT min (#PCDATA)>
<!ELEMENT rightCardinality (min|max)*>
<!ELEMENT max (#PCDATA)>

=== DSpace/DSpace/dspace/config/entities/correction-relationship-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE relationships SYSTEM "relationship-types.dtd">

<relationships>
    <type>
        <leftType>Person</leftType>
        <rightType>Person</rightType>
        <leftwardType>isCorrectionOfItem</leftwardType>
        <rightwardType>isCorrectedByItem</rightwardType>
        <leftCardinality>
            <min>0</min>
	    <max>1</max>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
	    <max>1</max>
        </rightCardinality>
    </type>
    <type>
        <leftType>Project</leftType>
        <rightType>Project</rightType>
        <leftwardType>isCorrectionOfItem</leftwardType>
        <rightwardType>isCorrectedByItem</rightwardType>
        <leftCardinality>
            <min>0</min>
	    <max>1</max>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
	    <max>1</max>
        </rightCardinality>
    </type>
    <type>
        <leftType>Funding</leftType>
        <rightType>Funding</rightType>
        <leftwardType>isCorrectionOfItem</leftwardType>
        <rightwardType>isCorrectedByItem</rightwardType>
        <leftCardinality>
            <min>0</min>
	    <max>1</max>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
	    <max>1</max>
        </rightCardinality>
    </type>
    <type>
        <leftType>OrgUnit</leftType>
        <rightType>OrgUnit</rightType>
        <leftwardType>isCorrectionOfItem</leftwardType>
        <rightwardType>isCorrectedByItem</rightwardType>
        <leftCardinality>
            <min>0</min>
	    <max>1</max>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
	    <max>1</max>
        </rightCardinality>
    </type>
    <type>
        <leftType>Journal</leftType>
        <rightType>Journal</rightType>
        <leftwardType>isCorrectionOfItem</leftwardType>
        <rightwardType>isCorrectedByItem</rightwardType>
        <leftCardinality>
            <min>0</min>
	    <max>1</max>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
	    <max>1</max>
        </rightCardinality>
    </type>
    <type>
        <leftType>Publication</leftType>
        <rightType>Publication</rightType>
        <leftwardType>isCorrectionOfItem</leftwardType>
        <rightwardType>isCorrectedByItem</rightwardType>
        <leftCardinality>
            <min>0</min>
	    <max>1</max>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
	    <max>1</max>
        </rightCardinality>
    </type>
    <type>
        <leftType>Patent</leftType>
        <rightType>Patent</rightType>
        <leftwardType>isCorrectionOfItem</leftwardType>
        <rightwardType>isCorrectedByItem</rightwardType>
        <leftCardinality>
            <min>0</min>
	    <max>1</max>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
	    <max>1</max>
        </rightCardinality>
    </type>
    <type>
        <leftType>Dataset</leftType>
        <rightType>Dataset</rightType>
        <leftwardType>isCorrectionOfItem</leftwardType>
        <rightwardType>isCorrectedByItem</rightwardType>
        <leftCardinality>
            <min>0</min>
	    <max>1</max>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
	    <max>1</max>
        </rightCardinality>
    </type>
    <type>
        <leftType>Event</leftType>
        <rightType>Event</rightType>
        <leftwardType>isCorrectionOfItem</leftwardType>
        <rightwardType>isCorrectedByItem</rightwardType>
        <leftCardinality>
            <min>0</min>
	    <max>1</max>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
	    <max>1</max>
        </rightCardinality>
    </type>
    <type>
        <leftType>Equipment</leftType>
        <rightType>Equipment</rightType>
        <leftwardType>isCorrectionOfItem</leftwardType>
        <rightwardType>isCorrectedByItem</rightwardType>
        <leftCardinality>
            <min>0</min>
	    <max>1</max>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
	    <max>1</max>
        </rightCardinality>
    </type>
    
</relationships>

=== DSpace/DSpace/dspace/config/entities/relationship-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE relationships SYSTEM "relationship-types.dtd">

<relationships>

	<!-- Sample relationship types setup used for the entities development
	 This file can be imported using the initialize-entities launcher -->
    <type>
        <leftType>Publication</leftType>
        <rightType>Person</rightType>
        <leftwardType>isAuthorOfPublication</leftwardType>
        <rightwardType>isPublicationOfAuthor</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToLeft>true</copyToLeft>
    </type>
    <type>
        <leftType>Publication</leftType>
        <rightType>Person</rightType>
        <leftwardType>isEditorOfPublication</leftwardType>
        <rightwardType>isPublicationOfEditor</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToLeft>true</copyToLeft>
    </type>
    <type>
        <leftType>Publication</leftType>
        <rightType>Project</rightType>
        <leftwardType>isProjectOfPublication</leftwardType>
        <rightwardType>isPublicationOfProject</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToLeft>true</copyToLeft>
    </type>
    <type>
        <leftType>Publication</leftType>
        <rightType>OrgUnit</rightType>
        <leftwardType>isOrgUnitOfPublication</leftwardType>
        <rightwardType>isPublicationOfOrgUnit</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToLeft>true</copyToLeft>
    </type>
    <type>
        <leftType>Person</leftType>
        <rightType>Project</rightType>
        <leftwardType>isProjectOfPerson</leftwardType>
        <rightwardType>isPersonOfProject</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
    </type>
    <type>
        <leftType>Person</leftType>
        <rightType>OrgUnit</rightType>
        <leftwardType>isOrgUnitOfPerson</leftwardType>
        <rightwardType>isPersonOfOrgUnit</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
    </type>
    <type>
        <leftType>Project</leftType>
        <rightType>OrgUnit</rightType>
        <leftwardType>isOrgUnitOfProject</leftwardType>
        <rightwardType>isProjectOfOrgUnit</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
    </type>
    <type>
        <leftType>Journal</leftType>
        <rightType>JournalVolume</rightType>
        <leftwardType>isVolumeOfJournal</leftwardType>
        <rightwardType>isJournalOfVolume</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
    </type>
    <type>
        <leftType>JournalVolume</leftType>
        <rightType>JournalIssue</rightType>
        <leftwardType>isIssueOfJournalVolume</leftwardType>
        <rightwardType>isJournalVolumeOfIssue</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
    </type>
    <type>
        <leftType>Publication</leftType>
        <rightType>OrgUnit</rightType>
        <leftwardType>isAuthorOfPublication</leftwardType>
        <rightwardType>isPublicationOfAuthor</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToLeft>true</copyToLeft>
    </type>
    <type>
        <leftType>Publication</leftType>
        <rightType>OrgUnit</rightType>
        <leftwardType>isEditorOfPublication</leftwardType>
        <rightwardType>isPublicationOfEditor</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToLeft>true</copyToLeft>
    </type>
    <type>
        <leftType>JournalIssue</leftType>
        <rightType>Publication</rightType>
        <leftwardType>isPublicationOfJournalIssue</leftwardType>
        <rightwardType>isJournalIssueOfPublication</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToRight>true</copyToRight>
    </type>
    <type>
        <leftType>Dataset</leftType>
        <rightType>Person</rightType>
        <leftwardType>isAuthorOfDataset</leftwardType>
        <rightwardType>isDatasetOfAuthor</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToLeft>true</copyToLeft>
    </type>
    <type>
        <leftType>Dataset</leftType>
        <rightType>Project</rightType>
        <leftwardType>isProjectOfDataset</leftwardType>
        <rightwardType>isDatasetOfProject</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToLeft>true</copyToLeft>
    </type>
    <type>
        <leftType>Dataset</leftType>
        <rightType>OrgUnit</rightType>
        <leftwardType>isAuthorOfDataset</leftwardType>
        <rightwardType>isDatasetOfAuthor</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToLeft>true</copyToLeft>
    </type>
    <type>
        <leftType>Dataset</leftType>
        <rightType>OrgUnit</rightType>
        <leftwardType>isOrgUnitOfDataset</leftwardType>
        <rightwardType>isDatasetOfOrgUnit</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToLeft>true</copyToLeft>
    </type>
    <type>
        <leftType>Dataset</leftType>
        <rightType>Publication</rightType>
        <leftwardType>isPublicationOfDataset</leftwardType>
        <rightwardType>isDatasetOfPublication</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
        <copyToLeft>true</copyToLeft>
        <copyToRight>true</copyToRight>
    </type>
    <type>
        <leftType>Funding</leftType>
        <rightType>Project</rightType>
        <leftwardType>isProjectOfFunding</leftwardType>
        <rightwardType>isFundingOfProject</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
    </type>
    <type>
        <leftType>Funding</leftType>
        <rightType>OrgUnit</rightType>
        <leftwardType>isOrgUnitOfFunding</leftwardType>
        <rightwardType>isFundingOfOrgUnit</rightwardType>
        <leftCardinality>
            <min>0</min>
        </leftCardinality>
        <rightCardinality>
            <min>0</min>
        </rightCardinality>
    </type>
</relationships>

=== DSpace/DSpace/dspace/config/entities/rioxx3-relationships.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE relationships SYSTEM "relationship-types.dtd">
<!-- Note that these relationships are the same as those for openaire4
 	They are used to map to relevant fields within the Rioxx profile. See docs below. -->
<relationships>

	<!-- https://www.rioxx.net/profiles/v3-0-final/#rioxxterms:creator
		The relation between a Publication and a Person regarding the authorship -->
	<type>
		<leftType>Publication</leftType>
		<rightType>Person</rightType>
		<leftwardType>isAuthorOfPublication</leftwardType>
		<rightwardType>isPublicationOfAuthor</rightwardType>
		<leftCardinality>
			<min>0</min>
		</leftCardinality>
		<rightCardinality>
			<min>0</min>
		</rightCardinality>
	</type>
	<!-- https://www.rioxx.net/profiles/v3-0-final/#rioxxterms:creator
		The relation between a Publication and an Organization regarding the authorship -->
	<type>
		<leftType>Publication</leftType>
		<rightType>OrgUnit</rightType>
		<leftwardType>isAuthorOfPublication</leftwardType>
		<rightwardType>isPublicationOfAuthor</rightwardType>
		<leftCardinality>
			<min>0</min>
		</leftCardinality>
		<rightCardinality>
			<min>0</min>
		</rightCardinality>
	</type>
	<!-- https://www.rioxx.net/profiles/v3-0-final/#rioxxterms:contributor
		The relation between a Publication and a Person regarding the contribution -->
	<type>
		<leftType>Publication</leftType>
		<rightType>Person</rightType>
		<leftwardType>isContributorOfPublication</leftwardType>
		<rightwardType>isPublicationOfContributor</rightwardType>
		<leftCardinality>
			<min>0</min>
		</leftCardinality>
		<rightCardinality>
			<min>0</min>
		</rightCardinality>
	</type>
	<!-- https://www.rioxx.net/profiles/v3-0-final/#rioxxterms:contributor
		The relation between a Publication and an Organization regarding the contribution -->
	<type>
		<leftType>Publication</leftType>
		<rightType>OrgUnit</rightType>
		<leftwardType>isContributorOfPublication</leftwardType>
		<rightwardType>isPublicationOfContributor</rightwardType>
		<leftCardinality>
			<min>0</min>
		</leftCardinality>
		<rightCardinality>
			<min>0</min>
		</rightCardinality>
	</type>
	<!--https://www.rioxx.net/profiles/v3-0-final/#rioxxterms:project
		The relation between a Publication and an Organization regarding the Funder to populate rioxxterms:project -->
	<type>
		<leftType>Publication</leftType>
		<rightType>Project</rightType>
		<leftwardType>isProjectOfPublication</leftwardType>
		<rightwardType>isPublicationOfProject</rightwardType>
		<leftCardinality>
			<min>0</min>
		</leftCardinality>
		<rightCardinality>
			<min>0</min>
		</rightCardinality>
	</type>
	<!-- https://www.rioxx.net/profiles/v3-0-final/#rioxxterms:grant
		The relation between a Funded Project and an Organization regarding the Funder to populate rioxxterms:grant -->
	<type>
		<leftType>Project</leftType>
		<rightType>OrgUnit</rightType>
		<leftwardType>isFundingAgencyOfProject</leftwardType>
		<rightwardType>isProjectOfFundingAgency</rightwardType>
		<leftCardinality>
			<min>0</min>
		</leftCardinality>
		<rightCardinality>
			<min>0</min>
		</rightCardinality>
	</type>

</relationships>
